Repository YU-SE-Team/meal-ticket-system-was, pull requests merged in 2025-09, with the labels that each got.

#21 feat:식당,티켓,메뉴 엔티티 생성
  build.gradle
  src/main/java/yuseteam/mealticketsystemwas/entity/Menu.java
  src/main/java/yuseteam/mealticketsystemwas/entity/Restaurant.java
  src/main/java/yuseteam/mealticketsystemwas/entity/Ticket.java
  src/main/resources/application.yml
Labels: For : Entity/DB, Type : Refactor

#36 [DB] JPA 중복 선언 수정
  src/main/java/yuseteam/mealticketsystemwas/admin/repository/RestaurantRepository.java
  src/main/java/yuseteam/mealticketsystemwas/domain/admin/controller/MenuController.java
  src/main/java/yuseteam/mealticketsystemwas/domain/admin/dto/MenuCreateRequest.java
  src/main/java/yuseteam/mealticketsystemwas/domain/admin/dto/MenuCreateResponse.java
  src/main/java/yuseteam/mealticketsystemwas/domain/admin/dto/MenuResponse.java
  src/main/java/yuseteam/mealticketsystemwas/domain/admin/entity/Menu.java
  src/main/java/yuseteam/mealticketsystemwas/domain/admin/repository/MenuRepository.java
  src/main/java/yuseteam/mealticketsystemwas/domain/admin/service/MenuService.java
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/config/SecurityConfig.java
  src/main/java/yuseteam/mealticketsystemwas/domain/restaurant/entity/Restaurant.java
  src/main/java/yuseteam/mealticketsystemwas/entity/Ticket.java
Labels: For : API, Type : Chore, Type : Bug, For : Entity/DB, Type : Refactor

#39 [QR] QR 저장 기능 (s3 연동)
  build.gradle
  src/main/java/yuseteam/mealticketsystemwas/config/S3Config.java
  src/main/java/yuseteam/mealticketsystemwas/domain/qr/controller/QrController.java
  src/main/java/yuseteam/mealticketsystemwas/domain/qr/service/S3Service.java
  src/main/resources/application.yml
Labels: For : API, Type : Feature, For : Entity/DB

#41 S3 region 변경
  src/main/resources/application.yml
Labels: Type : Chore, Type : Refactor

#46 [Menu] 메뉴 상세 조회
  src/main/java/yuseteam/mealticketsystemwas/domain/admin/controller/MenuController.java
  src/main/java/yuseteam/mealticketsystemwas/domain/admin/dto/MenuDetailResponseDto.java
  src/main/java/yuseteam/mealticketsystemwas/domain/admin/service/MenuService.java
Labels: For : API, Type : Feature, For : Entity/DB

#47 [Login] 로그아웃
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/controller/AuthController.java
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/service/InMemoryLogoutTokenService.java
Labels: For : API, Type : Feature

#63 [Menu] 주문 결제창 정보 조회
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/config/SecurityConfig.java
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/controller/AuthInitialSetupController.java
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/dto/UserDTO.java
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/entity/User.java
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/jwt/JWTFilter.java
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/repository/UserRepository.java
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/service/AuthInitialSetupService.java
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/service/CustomOAuth2UserService.java
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/service/UserService.java
  src/main/java/yuseteam/mealticketsystemwas/domain/order/controller/OrderController.java
  src/main/java/yuseteam/mealticketsystemwas/domain/order/dto/OrderConfirmationResponse.java
  src/main/java/yuseteam/mealticketsystemwas/domain/order/service/OrderService.java
Labels: For : API, Type : Feature

#66 [QR] QR 레이어 구조 변경
  src/main/java/yuseteam/mealticketsystemwas/domain/qr/controller/QrController.java
  src/main/java/yuseteam/mealticketsystemwas/domain/qr/dto/QrCreateResponse.java
  src/main/java/yuseteam/mealticketsystemwas/domain/qr/dto/QrInfoResponse.java
  src/main/java/yuseteam/mealticketsystemwas/domain/qr/dto/QrUseRequest.java
  src/main/java/yuseteam/mealticketsystemwas/domain/qr/service/S3Service.java
Labels: Type : Chore, Type : Bug, Type : Refactor
