Repository YU-SE-Team/meal-ticket-system-was, pull requests merged in 2025-10, with the labels that each got.

#91 [Order] 메뉴 주문 Entity 생성
  src/main/java/yuseteam/mealticketsystemwas/domain/order/entity/Order.java
  src/main/java/yuseteam/mealticketsystemwas/domain/order/entity/OrderItem.java
Labels: Type : Feature, For : Entity/DB

#100 [Order, Ticket] Order, OrderItem, Ticket DB 관계 추가
  src/main/java/yuseteam/mealticketsystemwas/domain/menu/entity/Menu.java
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/config/SecurityConfig.java
  src/main/java/yuseteam/mealticketsystemwas/domain/order/entity/OrderItem.java
  src/main/java/yuseteam/mealticketsystemwas/domain/order/service/OrderService.java
  src/main/java/yuseteam/mealticketsystemwas/domain/ticket/dto/PaymentRes.java
  src/main/java/yuseteam/mealticketsystemwas/domain/ticket/entity/Ticket.java
  src/main/java/yuseteam/mealticketsystemwas/domain/ticket/service/PaymentService.java
Labels: Type : Chore, For : Entity/DB, Type : Refactor

#102 [Auth] User Role 미설정으로 인한 JWTFilter NPE 발생
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/config/SecurityConfig.java
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/controller/AuthInitialSetupController.java
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/jwt/JWTFilter.java
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/service/AuthInitialSetupService.java
  src/main/java/yuseteam/mealticketsystemwas/domain/ticket/controller/PaymentController.java
Labels: Type : Chore, Type : Bug

#106 [Order] 즉석 합계 api의 수량 버그
  src/main/java/yuseteam/mealticketsystemwas/domain/order/service/OrderService.java
Labels: Type : Bug

#111 [Order] 메뉴 주문 기능 스웨거 작성
  src/main/java/yuseteam/mealticketsystemwas/config/GlobalExceptionHandler.java
  src/main/java/yuseteam/mealticketsystemwas/domain/order/controller/OrderController.java
  src/main/java/yuseteam/mealticketsystemwas/domain/order/dto/CreateOrderReq.java
  src/main/java/yuseteam/mealticketsystemwas/domain/order/dto/OrderConfirmationRes.java
  src/main/java/yuseteam/mealticketsystemwas/domain/order/dto/OrderCreatedRes.java
  src/main/java/yuseteam/mealticketsystemwas/domain/order/dto/OrderSummaryRes.java
Labels: Type : Chore

#112 [Menu] 5분마다 판매량 조회
  gradlew
  src/main/java/yuseteam/mealticketsystemwas/MealTicketSystemWasApplication.java
  src/main/java/yuseteam/mealticketsystemwas/domain/menu/controller/MenuSalesSnapshotController.java
  src/main/java/yuseteam/mealticketsystemwas/domain/menu/dto/MenuSalesDiffRes.java
  src/main/java/yuseteam/mealticketsystemwas/domain/menu/entity/MenuSalesSnapshot.java
  src/main/java/yuseteam/mealticketsystemwas/domain/menu/repository/MenuSalesSnapshotrepository.java
  src/main/java/yuseteam/mealticketsystemwas/domain/menu/service/MenuSalesSnapshotService.java
Labels: For : API, Type : Feature, For : Entity/DB

#122 [Menu] 인기메뉴 조회
  src/main/java/yuseteam/mealticketsystemwas/domain/menu/controller/MenuSalesSnapshotController.java
  src/main/java/yuseteam/mealticketsystemwas/domain/menu/dto/PopularMenuListRes.java
  src/main/java/yuseteam/mealticketsystemwas/domain/menu/repository/MenuRepository.java
  src/main/java/yuseteam/mealticketsystemwas/domain/menu/repository/MenuSalesSnapshotrepository.java
  src/main/java/yuseteam/mealticketsystemwas/domain/menu/service/MenuSalesSnapshotService.java
Labels: For : API, Type : Feature

#135 [Menu] Swagger 수정
  src/main/java/yuseteam/mealticketsystemwas/domain/menu/admin/controller/AdminMenuController.java
  src/main/java/yuseteam/mealticketsystemwas/domain/menu/customer/controller/MenuController.java
  src/main/java/yuseteam/mealticketsystemwas/domain/menu/sales/controller/MenuSalesSnapshotController.java
  src/main/java/yuseteam/mealticketsystemwas/domain/oauthjwt/controller/OAuth2LoginController.java
  src/main/java/yuseteam/mealticketsystemwas/domain/order/controller/OrderController.java
  src/main/java/yuseteam/mealticketsystemwas/domain/ticket/controller/TicketController.java
Labels: Type : Chore
